#ifndef COMMON_DEFINITIONS_HH
#define COMMON_DEFINITIONS_HH

#define BLOCK_SIZE 4096
#define STORAGE_FILE_SIZE_MB 1024

// Addresses to trigger instrumented crash behavior on server
#define PREP_CRASH_ON_MESSAGE_PRIMARY 0x10000u
#define PREP_CRASH_ON_MESSAGE_BACKUP 0x11000u
#define CRASH_PRIMARY_BEFORE_BACKUP 0x12000u
#define CRASH_PRIMARY_AFTER_WRITE 0x13000u
#define CRASH_BACKUP_DURING_BACKUP 0x14000u
#define CRASH_BACKUP_AFTER_BACKUP 0x15000u
#define PREP_CRASH_ON_NEXT_RECOVER 0x16000u

#endif